# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='cover_images/cover.jpg', upload_to='cover_images'),
        ),
    ]
