# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_auto_20170515_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
