# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0006_auto_20170516_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='quote',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
