# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0007_auto_20170516_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='pub_date',
            new_name='published_date',
        ),
    ]
