# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0008_auto_20170516_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[("didn't like it so much", 'Not really'), ("is'nt sure about it", 'so-so'), ('Loved it!', 'Loved it!')]),
        ),
    ]
