# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0009_auto_20170516_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Not really'), (2, 'so-so'), (3, 'Loved it!')]),
        ),
    ]
