# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0012_remove_review_rating_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='illustrator',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
