# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0015_auto_20170516_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='wiki_page',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
