# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0016_book_wiki_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='wiki_page',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, default=2017),
        ),
    ]
