# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0018_auto_20170518_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review1',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review1',
        ),
    ]
