# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 21:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0020_readere_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readere',
            name='user',
            field=models.OneToOneField(default='A', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
