# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0028_auto_20170518_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readere',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'not/specified')], default='not/specified', max_length=1),
        ),
    ]
