# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0029_auto_20170518_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readere',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'Other /not specified')], default='O', max_length=1),
        ),
    ]
