# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0030_auto_20170519_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
